name: CI

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  # causes CI to fail on any warning
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Rust (nightly)
      run: |
        rustup install nightly
        rustup override set nightly
        rustup component add --toolchain nightly rustfmt clippy
    - name: cargo fmt
      run: cargo fmt --all -- --check
    - name: cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: cargo test
      run: cargo test --verbose

  library_checker_aizu_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: install oj-verify
      run: pip3 install -U online-judge-verify-helper
    - name: use oj-verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify all --tle 1 --jobs 4 --timeout 3600
